### ISSUE TITLE
[DOC]: Include an explanation of the repo structure

### ISSUE THREAD

**Issue by randerzander** [NVIDIA/nv-ingest#29]
### How would you describe the priority of this documentation request

Significant improvement

### Please provide a link or source to the relevant docs

github.com/nvidia/nv-ingest

### Describe the problems in the documentation

We should depict the tree structure of the GitHub repo as well as clearly document what each directory contains.

This will help promote discoverability of the different components and help a user better understand and navigate the repository. For example, there is README in the client directory, which is not easily discoverable because the user does not know what the client directory holds and is used for. Similarly, the support for deployment using the helm chart is not easily discoverable either.

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
