### ISSUE TITLE
[DOC]: Include minimum hardware requirements in the Helm README

### ISSUE THREAD

**Issue by randerzander** [NVIDIA/nv-ingest#31]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

github.com/nvidia/nv-ingest

### Describe the problems in the documentation

The helm chart deployment needs to note the minimum hardware and software requirements necessary.

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
