### ISSUE TITLE
[DOC]: clarify the reason for 'pip install e .' command

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#33]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest?tab=readme-ov-file#step-2-installing-python-dependencies:~:text=r%20./requirements.txt-,pip%20install%20e%20.,-Step%203%3A%20Ingesting

### Describe the problems in the documentation

Users are asked to run `pip install e .` to install the packages in editable mode. It is not clear why this is the case and if required,.

**Comment by randerzander** [comment]
Closed by #80
