### ISSUE TITLE
[DOC]: Add the expected 'docker ps' command output for users to validate post-deployment

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#34]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/main/README.md

### Describe the problems in the documentation

The README should describe what the output of the `docker ps` command should look like after bringing up the workflow so that users know which containers should be up. The logs will be much harder to follow since there are multiple containers so it will be harder to catch any errors. Add the expected output of the docker ps command as a way for the users to validate that all the containers came up successfully.

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
