### ISSUE TITLE
[DOC]: remove 'python3' process from the expected nvidia-smi output

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#35]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/main/README.md#:~:text=When%20all%20services%20have%20fully%20started%2C%20nvidia%2Dsmi%20should%20show%20processes%20like%20the%20following

### Describe the problems in the documentation

The output of the nvidia-smi command that is given in the README shows `/opt/nim/llm/.venv/bin/python3` process running which is not the case.

**Comment by randerzander** [comment]
This is incorrect. This is one of the processes run inside the Deplot NIM container
