### ISSUE TITLE
[DOC]: clarfiy the optionallity of Milvus in the introduction

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#36]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/main/README.md

### Describe the problems in the documentation

The line in the documentation in the introduction is not sufficient in conveying to a user that Milvus is optional in the deployment.

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
