### ISSUE TITLE
[DOC]: Use secrets for the helm chart repo credentials

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#39]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/tree/main/helm#:~:text=namespace%20%24%7BNAMESPACE%7D-,Install%20the%20chart,-helm%20upgrade%20%5C%0A%20%20%20%20%2D%2Dinstall

### Describe the problems in the documentation

eliminate the need to use `--username` and `--password` flags

**Comment by jdye64** [comment]
The `--username` and `--password` arguments are required by Helm to access the protected Helm chart. There is currently no support for using secrets with Helm for that interaction.
