### ISSUE TITLE
[DOC]: Add example code snippet on how to use a llama-index or langchain doc query pipeline

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#40]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/tree/main#:~:text=Beyond%20inspecting%20the%20results%2C%20you%20can%20read%20them%20into%20something%20like%20a%20llama%2Dindex%20or%20langchain%20document%20query%20pipeline

### Describe the problems in the documentation

The following line in the README “Beyond inspecting the results, you can read them into something like a llama-index or langchain document query pipeline:” should be followed with an example code snippet of how this can be accomplished.

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
