### ISSUE TITLE
[DOC]: Add example usage for all API libraries

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#41]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/main/client/README.md#api-libraries:~:text=API%20and%20CLI.-,API%20Libraries,-nv_ingest_client.primitives.jobs

### Describe the problems in the documentation

Only the first two API libraries have example usage. Add example code snippets for all the libraries

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
