### ISSUE TITLE
[DOC]: Revise the output of the sample document ingestion script

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#45]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/tree/main

### Describe the problems in the documentation

The output of the sample document ingestion script is unintuitive. There is no clarity on what is expected from this script. There are just lines that say which jobs are submitted and some lines that look like debug lines. This output needs to be revised to be more user-friendly.

**Comment by randerzander** [comment]
This was resolved during the client refactor. #84 also adds a README comment explaining the output's signficance

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
