### ISSUE TITLE
[DOC]: Remove the placeholders in the README

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#46]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/main/client/README.md#:~:text=Usage-,TODO,-(Devin)%3A%20Need%20to

### Describe the problems in the documentation

There are still placeholders in the README. Both “[Examples](https://github.com/NVIDIA/nv-ingest/blob/main/client/README.md#:~:text=Supports%20multiple%20tasks.-,Examples,-Examples%20of%20using)” and “[Configuration](https://github.com/NVIDIA/nv-ingest/blob/main/client/README.md#:~:text=execute%20different%20tasks.-,Configuration,-Details%20on%20how)” sections are empty. Therefore due to the missing example usage of CLI tool, a user does not know the different uses for which it can be used.
There's also a TODO [here](https://github.com/NVIDIA/nv-ingest/blob/main/client/README.md#:~:text=Usage-,TODO,-(Devin)%3A%20Need%20to) that should be removed.

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
