### ISSUE TITLE
[DOC]: Number the deployment steps

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#47]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/main/README.md#:~:text=Step%201%3A%20Starting%20containers

### Describe the problems in the documentation

In [step 1](https://github.com/NVIDIA/nv-ingest/blob/main/README.md#:~:text=Step%201%3A%20Starting%20containers), convert the deployment steps to a numbered list for better readability,

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
