### ISSUE TITLE
[DOC]: Add instructions on how to control the logs per service

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#50]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/tree/main#:~:text=You%20can%20control%20this%20on%20a%20per%20service%20level%20via%20each%20service%27s%20environment%20variables

### Describe the problems in the documentation

The documentation says that the logs can be controlled on a per service level basis [here](https://github.com/NVIDIA/nv-ingest/tree/main#:~:text=You%20can%20control%20this%20on%20a%20per%20service%20level%20via%20each%20service%27s%20environment%20variables). Besides just saying that it is possible, the instructions on how to do this should be documented

**Comment by jdye64** [comment]
Closed with https://github.com/NVIDIA/nv-ingest/pull/84
