### ISSUE TITLE
[DOC]: Clean up the copy/paste command on code snippets

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#51]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/tree/main?tab=readme-ov-file#step-4-inspecting-and-consuming-results:~:text=Step%204%3A%20Inspecting%20and%20Consuming%20Results

### Describe the problems in the documentation

Copy/paste for some commands and code snippets are not configured correctly. For example, for [this command](https://github.com/NVIDIA/nv-ingest/tree/main?tab=readme-ov-file#step-4-inspecting-and-consuming-results:~:text=Step%204%3A%20Inspecting%20and%20Consuming%20Results), a user would end up copying both the input and expected output by clicking on the “Copy” icon.

**Comment by randerzander** [comment]
Resolved already
