### ISSUE TITLE
[DOC]: Clarify the intent of the seemingly no-op 'as_completed' for loop

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#58]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/359ed541e0a2fdc117ee6e637b5d4ef433c5589e/client/examples/sample_job.py#L190

### Describe the problems in the documentation

[This part](https://github.com/NVIDIA/nv-ingest/blob/359ed541e0a2fdc117ee6e637b5d4ef433c5589e/client/examples/sample_job.py#L190) of the code
Seems like `as_completed(arg)` actually executes a function which guarantees that the job is complete upon execution. So it's not really no-op, if so please add a comment to that effect

**Comment by randerzander** [comment]
sample_job.py was removed, closing as no longer relevant
