### ISSUE TITLE
[DOC]: Please better document/clarify the steps required to run the image viewer tool

### ISSUE THREAD

**Issue by sosahi** [NVIDIA/nv-ingest#59]
### How would you describe the priority of this documentation request

None

### Please provide a link or source to the relevant docs

https://github.com/NVIDIA/nv-ingest/blob/main/src/util/image_viewer.py

### Describe the problems in the documentation

It requires `tkinter` which is not included in the requirements.txt file user is instructed to install

**Comment by randerzander** [comment]
README now includes pip install tkinter step
