### ISSUE TITLE
[FEA]: Add python multi file API for job submission

### ISSUE THREAD

**Issue by randerzander** [NVIDIA/nv-ingest#78]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Significant improvement

### Please provide a clear description of problem this feature solves

Our current Python job submission API operates on single files at a time (https://github.com/nvidia/nv-ingest?tab=readme-ov-file#step-3-ingesting-documents)

For those concerned w/ maximum throughput, this might suggest suboptimal performance.

### Describe the feature, and optionally a solution or implementation and any alternatives

We should provide a Python API that supports submitting multiple files at once.

It should support both lists of files, and a directory.

### Additional context

Edit (Devin): Some additional baseline considerations:

- [ ]  Support for multi-file submission and handling
  - [ ] Add an interface for replicating a dictionary mapping or equivalent of file_type->JobSpec across multiple files
  - [ ] Creation of file list via path globbing or dataset specification
  - [ ] Interface for generating Jobs from a set of files and JobSpecs
- [ ] Performance and Parallelism 
  - [ ] Configurable in-flight batch size
  - [ ] Ensure we have builtin fetch attempt / retry logic and the ability for an end user to specify fetch timeouts; this is related to the idea that timeouts against the fetch endpoint are not failures, rather they're just indicators that a job has not finished yet.
  - [ ] (optional) Add native async calls in addition to Futures based async functionality
- [ ] Error handling
  - [ ] Add in the ability to check and handle failed jobs 'metadata.status' == failed

**Comment by jperez999** [comment]
Is there a way we could add a lambda read function. What I am trying to do here is support use cases that may be outside the target right now. We are currently heavy on supporting pdf files. It would be good if we could supply an optional lambda to this api that extracted the content as a list and that list could be processed into JobSpecs. The goal here would be to allow other filetypes like jsonl, dataframes, numpy files and other custom formats. 

For instance for jsonl files I used the following simple method to load data:
```
import json

def load_json(file_path): 
    data_json = []
    with open(file_path) as json_data:
        for line in json_data:
            j_line = json.loads(line)
            data_json.append((j_line['_id'], j_line['text']))
    return data_json
```
Feel free to push back.

**Comment by drobison00** [comment]
> Is there a way we could add a lambda read function. What I am trying to do here is support use cases that may be outside the target right now. We are currently heavy on supporting pdf files. It would be good if we could supply an optional lambda to this api that extracted the content as a list and that list could be processed into JobSpecs. The goal here would be to allow other filetypes like jsonl, dataframes, numpy files and other custom formats.
> 
> For instance for jsonl files I used the following simple method to load data:
> 
> ```
> import json
> 
> def load_json(file_path): 
>     data_json = []
>     with open(file_path) as json_data:
>         for line in json_data:
>             j_line = json.loads(line)
>             data_json.append((j_line['_id'], j_line['text']))
>     return data_json
> ```
> 
> Feel free to push back.

@jperez999 This is similar in process to what the CLI tool does now; there is probably a good argument for taking some of the CLI specific implementations available now, making them more generic, and including them as a higher level interface in the Python library.
